// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWhG1Tyd_yypkf7nbWPmIZUWjdtNWgEPc',
    appId: '1:445139054884:web:9ad2e296cca62a077943b1',
    messagingSenderId: '445139054884',
    projectId: 'spendly-e50d0',
    authDomain: 'spendly-e50d0.firebaseapp.com',
    storageBucket: 'spendly-e50d0.firebasestorage.app',
    measurementId: 'G-5Q55Y0VW2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDltOYXkfyNl8R5AK7vHRh1DOy5t1behPk',
    appId: '1:445139054884:android:135e4fb1c77a6fda7943b1',
    messagingSenderId: '445139054884',
    projectId: 'spendly-e50d0',
    storageBucket: 'spendly-e50d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_MG1OAnMlOnnimy_jIlTNF-UZKaFTOo',
    appId: '1:445139054884:ios:73a3ea55f312e3ea7943b1',
    messagingSenderId: '445139054884',
    projectId: 'spendly-e50d0',
    storageBucket: 'spendly-e50d0.firebasestorage.app',
    androidClientId: '445139054884-ig58aq70kmnv9199m49qpd5fk3gs5b6v.apps.googleusercontent.com',
    iosClientId: '445139054884-f3j6gop2nh93f5emn0b6afhtmh5b2atp.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_MG1OAnMlOnnimy_jIlTNF-UZKaFTOo',
    appId: '1:445139054884:ios:73a3ea55f312e3ea7943b1',
    messagingSenderId: '445139054884',
    projectId: 'spendly-e50d0',
    storageBucket: 'spendly-e50d0.firebasestorage.app',
    androidClientId: '445139054884-ig58aq70kmnv9199m49qpd5fk3gs5b6v.apps.googleusercontent.com',
    iosClientId: '445139054884-f3j6gop2nh93f5emn0b6afhtmh5b2atp.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWhG1Tyd_yypkf7nbWPmIZUWjdtNWgEPc',
    appId: '1:445139054884:web:999c36db468758037943b1',
    messagingSenderId: '445139054884',
    projectId: 'spendly-e50d0',
    authDomain: 'spendly-e50d0.firebaseapp.com',
    storageBucket: 'spendly-e50d0.firebasestorage.app',
    measurementId: 'G-JGQ8KWBFKL',
  );
}
